services:
  dribdat:
    image: dribdat/dribdat
    container_name: dribdat-web
    restart: unless-stopped
    ports:
      - 5123:5000
    environment:
      - SERVER_URL=localhost.changeme:5123
      - DATABASE_URL=postgres://dribdat_user:changeme@db:5432/dribdat
      - DRIBDAT_ENV=prod
      - DRIBDAT_SECRET=changeme
      - DRIBDAT_APIKEY=changeme
      - TIME_ZONE=Europe/Zurich
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dribdat
      - POSTGRES_USER=dribdat_user
      - POSTGRES_PASSWORD=changeme

