---
# definition of rulesets for advancing through the stages of a dribdat project

stages:
  -
    id: 0
    name: CHALLENGE
    phase: Challenge
    description: 🚧 Define questions to answer with data about issues that matter.
    tip: Advance to the next stage by posting an update.
    conditions:
      validate:
        -
          field: summary
          min: 5
          help: Your challenge should have a short summary.
        -
          field: excerpt
          min: 123
          help: Write at least one paragraph (123 chars) in the Pitch or upload a few sketches.
      agree:
        - Your questions hint at what data will be needed, helping to scope the project.
        - Acquiring data to meet the challenge is realistic within our time limits.
  -
    id: 5
    name: PROJECT
    phase: Project
    description: 👪 Collecting resources together in a shared space.
    tip: Find examples and resources to inspire your team.
    conditions:
      validate:
        -
          field: team
          min: 1
          max: 5
          help: Between 1 and 5 people should Join your project or expedition.
      agree:
        - Our team members have agreed to work together for the duration of the event.
        - We are obtaining data, and sharing it in a space accessible to everyone.
  -
    id: 10
    name: RESEARCH
    phase: Research
    description: ⚗️ Scoping of data collection and prototyping strategy.
    tip: Write down what you are doing regularly to stay on track.
    conditions:
      validate:
        -
          field: source_url
          test: validurl
          help: Provide a source link in your project Details.
      agree:
        - Check the metadata and context of your data, the credibility of your sources.
        - A shared repository has been set up, your work on code and data is backed up.
  -
    id: 20
    name: SKETCH
    phase: Sketching
    description: 🎨 Evaluating and explaining to humans and machines.
    tip: The more you share, the more feedback you will get.
    conditions:
      validate:
        -
          field: image_url
          test: validurl
          help: Upload or link to an image in your project Details.
      agree:
        - Annotate key datasets to reflect your understanding of the structure and content.
        - Make wireframes or sketches of your idea, attaching it as an image to your documentation.
  -
    id: 30
    name: PROTOTYPE
    phase: Prototype
    description: 🐣 Efforts to improve the quality of the output.
    tip: There is no such thing as a stupid question. Just ask if you are stuck.
    conditions:
      validate:
        -
          field: webpage_url
          test: validurl
          help: Online access to see your presentation, dataset or demo in the Project Link.
      agree:
        - Gain more depth by exploring the data with visualisations and interactive interfaces.
        - We have checked permissions to use all assets, data, or code, and linked the sources.
  -
    id: 40
    name: LAUNCH
    phase: Launch
    description: 🎈 Gaining insights on the problem defined in the beginning.
    tip: Make sure to give credit to everyone involved and document all sources used.
    conditions:
      validate:
        -
          field: contact_url
          test: validurl
          help: Provide a contact link in your project Details.
      agree:
        - While correlating and linking data fields, we are critical of causality.
        - Contact with the maintainers is possible to ask questions or send feedback.
  -
    id: 50
    name: LIVE
    phase: Share
    description: 🚀 Thinking about audience and making the results public.
    tip: Think of next steps and action points (take-aways) from your work.
    conditions:
      validate:
        -
          field: download_url
          test: validurl
          help: Provide a download link in your project Details.
      agree:
        - The full results of this work have been showcased and published under an open license.
        - We have correctly attributed all sources, and thanked all contributors.
